Windows ami Integration tests updates
psharkey/ansible pull request #7
Opened 2019-09-15 19:49 UTC by hanumantharaomvl

##### SUMMARY
This PR contains the following fixes.

1. Windows AMI Update for Integration Tests.
2. Windows Integration tests updates.

Validated the changes.

2019-09-19 19:00 UTC, psharkey requested changes

2019-09-19 19:00 UTC, psharkey commented on test/integration/targets/connection/test_connection.yml
> -    fetch: src={{ remote_tmp }}-汉语/汉语.txt dest={{ local_tmp }}-汉语/汉语.txt fail_on_missing=true validate_checksum=true flat=true
What's the reasoning behind removing this task?

2019-09-19 19:00 UTC, psharkey commented on test/integration/targets/connection_aws_ssm/aws_ssm_integration_test_setup/tasks/main.yml
> -      no_log: yes
Won't this leak credentials to the console now?

2019-09-19 19:00 UTC, psharkey commented on test/integration/targets/connection_aws_ssm/aws_ssm_integration_test_teardown/tasks/main.yml
> -  no_log: true
Same as above - looks like this exposes credentials now.

2019-10-29 13:12 UTC, hanumantharaomvl commented
Changes were already checked-in. Closing the PR.

2019-10-29 13:12 UTC, closed without merging